Docs: Fix typo on dirname in README.md
I believe this should be `spec/pact/providers/**` instead of `spec/pact/provider/**`
as the README.md file states.

Not having it in `spec/pact/providers/**`` will cause the consumer tests to
not run with a confusing error message like:
```
NoMethodError:
  undefined method 'has_http_pact_between' for class RSpec::ExampleGroups...
```